### ISSUE TITLE
Updating to GCP

### ISSUE THREAD

**Issue by rijvirajib** [arkie/dicebot#52]
I am trying to run this on my own since I have some changes I'd like that is not worth pushing (setting `mini` to default)

I am having a lot of errors getting this going. Has this been updated to support the latest GCP?
Examples are:

- No more `api_version`
- `runtime` should be changed to a specific go version like `go111`

**Comment by arkie** [comment]
It has not! It's been a task on my backlog for awhile since Slack is deprecating what appears to be the version of TLS used by Appengine (at least at the time of last deploy).

It did seem to deploy successfully on last commit (https://circleci.com/gh/arkie/dicebot/138 - about six months ago) which you can see the command being run in question on CircleCI (in case you're using a different toolchain).

If you get it modernized, would be happy to look at a PR, otherwise I'll look at updating it in the next few days.

**Comment by rijvirajib** [comment]
Thanks, I will give it a shot!

**Comment by rijvirajib** [comment]
Thank you. I will give it a go, but having bad luck with the new go112 environment.
